### ISSUE TITLE
Chained transformations

### ISSUE THREAD

**Issue by Krato** [thumbor/thumbor#1008]
Hello I just want to ask (cause I not found), if thumbor can make chain transformations.

For example, if I want to resize an image and then crop it based in the new resized image.

Thanks so much!

**Comment by marcelometal** [comment]
Hi @Krato , yes you can. Take a look here to find out more about it:
http://thumbor.readthedocs.io/en/latest/usage.html

**Comment by Krato** [comment]
Hi @marcelometal . Thanks, but I don't see this feature in the documents.

**Comment by marcelometal** [comment]
Please try it: `http://your-thumbor-server/AxB:CxD/800x600/http://img-url`

AxB:CxD means manually crop the image at left-top point AxB and right-bottom point CxD

**Comment by heynemann** [comment]
@Krato in order to chain several transforms, just pass a thumbor URL to thumbor itself, like:

http://thumbor/unsafe/300x200/http://thumbor/unsafe/800x300/my/image.jpg

You can chain as many as you'd like and thumbor will cache all the intermediate steps.

If you have any further questions on this subject, please reopen this issue.

**Comment by Krato** [comment]
Thanks @heynemann. Thats what I thought. 👍
