### ISSUE TITLE
Problem with svg

### ISSUE THREAD

**Issue by SergioJorge** [thumbor/thumbor#1039]
### Thumbor request URL
http://<thumbor_url>/unsafe/<path_to_image>/7b9f1630b40b315d.svg

### Expected behaviour
Return a valid svg.

### Actual behaviour
Thumbor return a 500.
`thumbor:ERROR [BaseHandler] get_image failed for urlhttp://<thumbor_url>/unsafe/<path_to_image>/7b9f1630b40b315d.svg. error: float division by zero
`

Cairosvg raise a error when a svg have a mask without width.

This is the file in txt because github does not accept svg files.
[7b9f1630b40b315d.svg.txt](https://github.com/thumbor/thumbor/files/1704261/7b9f1630b40b315d.svg.txt)

### Operating system
OSx, Ubuntu, etc

### Your thumbor.conf
Default.

**Comment by HC-Team** [comment]
Hey have exact the same problem, svg is valid but thumbor hits the floor.

**Comment by HC-Team** [comment]
By the way, installing cairosvg ``pip3 install cairosvg`` alongside ``cair`` && ``libffi`` did NOT help, also not installing thumbor after that.

**Comment by kkopachev** [comment]
works for me with thumbor==6.4.1 and CairoSVG==1.0.22

**Comment by jmif** [comment]
Having the same issue with thumbor==6.4.2 and CairoSVG==1.0.22, my SVG has a mask with without a width as well.

Was there any resolution or workaround found for this @SergioJorge?

**Comment by Tenzer** [comment]
In my experience, in order to get SVG files to work, you need to make sure both the `CairoSVG` and `pycairo` packages are installed. However, if you are on Python 2 you want to makes sure you get `CairoSVG 1.x` (1.0.22 being the latest at the time of writing) as the 2.x versions don't have support for Python 2.

However, CairoSVG in version 1.0.22 has a bug which is fixed in the 2.x versions but hasn't been backported. It was reported [here](https://github.com/Kozea/CairoSVG/issues/86) and the fix is [here](https://github.com/Kozea/CairoSVG/commit/b73b3f1a98382038b573151985a77d40ef13c531).

I guess we need to get Python 3 support for Thumbor fixed before we can hope for this to be solved.

**Comment by hrhitesh** [comment]
I have the same issues that I can not upload the SVG file using the curl command. 
Here is my CURL:
curl -v -i -XPOST https://myupload.example.com/image -F "media=@test.svg" and it gives me the error 
< HTTP/1.1 415 Unsupported Media Type
HTTP/1.1 415 Unsupported Media Type

**Comment by iwanskit** [comment]
hi @hrhitesh did you finally find out why svg doesnt work?

**Comment by hrhitesh** [comment]
@iwanskit no I don't.
