### ISSUE TITLE
Request for Python 3.6+ Support.

### ISSUE THREAD

**Issue by amanagr** [thumbor/thumbor#1280]
As per the release notes, thumbor now supports Python 3.7+ only. Will thumbor support Python 3.5+ in future? What problems are you guys facing when supporting python 3.5+?

I am one of the contributors from Zulip(https://github.com/zulip) and we would love to have Python 3.5+ support in thumbor as we rely on thumbor heavily.

**Comment by timabbott** [comment]
To provide a bit of background, Zulip doesn't ship its own Python -- we use whatever comes with the base OS.  So the requirement for Python 3.7+ only means that we'd need to switch to bundling Python, since even the latest Ubuntu LTS (18.04) has only 3.6.

I think Thumbor should follow the standard for other Python packages of supporting everything that's not EOL.  In case 3.5 is technically difficult, at least bringing the minimum supported Python to 3.6+ would be very meaningful; while 3.5 will reach EOL in ~6 months, 3.6 will be with us through all of 2021.

**Comment by heynemann** [comment]
Would you be willing to help with supporting 3.6? I don't think it's hard, there was something that was not working in 3.6 that made us switch to 3.7, but it was a minor thing.

**Comment by timabbott** [comment]
I won't speak for @amanagr but I expect so!

Do you expect we'll find any issues by just running the thumbor test suite, or is there another process you'd use for verifying work on this?

**Comment by heynemann** [comment]
I’d run pylint

**Comment by amanagr** [comment]
I will try to help support python 3.6. Let me locate the issue first with py3.6.

**Comment by amanagr** [comment]
I think the issue is this:
```
thumbor/threadpool.py:47:15: E1101: Module 'asyncio' has no 'get_running_loop' member (no-member)
```
`get_running_loop` function is new in python 3.7 as per docs: https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.get_running_loop

I will try and see how we can work around it.

**Comment by kkopachev** [comment]
try `tornado.ioloop.IOLoop.current()`
