### ISSUE TITLE
fit-in with ExH sizing does not resize appropriately

### ISSUE THREAD

**Issue by Manish-Muttreja-Bose** [thumbor/thumbor#1310]
### Thumbor request URL
(hostremoved)/fit-in/200x200/https://ibb.co/SBBhhgh 

### Expected behaviour
I should get an image of size 200x200 but I end up with a non-square picture.
The image i get is https://ibb.co/1f2K1ZS 

### Operating system
Doesn't matter

### Your thumbor.conf
Default with a different security key

**Comment by heynemann** [comment]
I can't view the original image. Would be helpful to understand what's going on with fit-in...

**Comment by heynemann** [comment]
Just to put the way the docs say it here:

```
fit-in means that the generated image should not be auto-cropped and otherwise just fit in an imaginary box specified by ExF. If a full fit-in is specified, then the largest size is used for cropping (width instead of height, or the other way around). If adaptive fit-in is specified, it inverts requested width and height if it would get a better image definition;
```

Checking the results with this original image:

https://camo.githubusercontent.com/92e3a4e87a65eb10946943d8a0b19819a0f8356d37935f441bd86c616c26553b/68747470733a2f2f7261772e6769746875622e636f6d2f7468756d626f722f7468756d626f722f6d61737465722f6c6f676f2d7468756d626f722e706e67

When running thumbor with `fit-in/200x200/<image-url>` I get an image with 200x61. When doing it with `full-fit-in/200x200/<image-url>` I get an image with 651x200.

If you want an image with 200x200 and fitting inside of it your image, you need to tell thumbor to do it with `/fit-in/200x200/filters:fill(transparent)/` (or any color instead of transparent).

For the docs on fill filter: https://thumbor.readthedocs.io/en/latest/filling.html

If you still have questions, please reopen the question and sorry it took so long to reply.
