### ISSUE TITLE
AVIF support

### ISSUE THREAD

**Issue by allantatter** [thumbor/thumbor#1314]
Could [AVIF](https://jakearchibald.com/2020/avif-has-landed/) support expected to be added at some point similarly to `webp` in [format](https://thumbor.readthedocs.io/en/stable/format.html#format) filters?

**Comment by franek** [comment]
Hi,
We would really appreciate that Thumbor does support AVIF format. 
* How could we help to achieve that ? 
* What are the requirements ? Is this PR on Pillow required https://github.com/python-pillow/Pillow/pull/4782 ? 
Thanks,

**Comment by fdintino** [comment]
I opened python-pillow/Pillow#5201, which would make it possible for thumbor to support the format.

**Comment by Tsouef** [comment]
Any news ?

**Comment by gladson** [comment]
https://github.com/libvips/libvips

It supports a good range of image formats, including JPEG, JPEG2000, JPEG-XL, TIFF, PNG, WebP, HEIC, AVIF, FITS, Matlab, OpenEXR, PDF, SVG, HDR, PPM / PGM / PFM, CSV, GIF, Analyze, NIfTI, DeepZoom, and OpenSlide.

**Comment by scorphus** [comment]
You can try the [ImagaMagick engine](https://github.com/scorphus/thumbor-wand-engine). You'll need Thumbor from master, though. Let me know if it works, please.

**Comment by fdintino** [comment]
It's been taking a while to get the pillow PR merged. To be fair to the pillow developers, it's not a trivial new feature. Until that PR lands I've created a standalone package, [pillow-avif-plugin](https://github.com/fdintino/pillow-avif-plugin), that adds AVIF support to Pillow. Also, unlike my pillow PR—which only works in python 3—my standalone package has wheels built against python 2. This is because the latest stable version of thumbor is still python 2-only.

I'm currently testing out an extension of thumbor and [thumbor-video-engine](https://github.com/theatlantic/thumbor-video-engine) on https://www.theatlantic.com/ that adds auto-AVIF support. If you visit the site in chrome, you'll see a bunch of AVIF images being served in the Network tab in the web inspector. The source code for that isn't publicly available, but if it goes well I'm planning on creating a package for it.

**Comment by vanchung1995** [comment]
@fdintino I have used pillow avif plugin, it worked nice. But I dont know how to apply it into thumbor. Example I want to crop image, then convert it to avif image. I read a lots but nothing found. Can you give some guide? Thanks so much

**Comment by mvhirsch** [comment]
AVIF is spreading, see https://caniuse.com/?search=avif

Bumping this issue (stale-bot :tada: )

**Comment by heynemann** [comment]
I will [bootcamp](https://github.com/thumbor/thumbor-bootcamp) this task later. This seems like a good L3 task.

**Comment by heynemann** [comment]
I would @fdintino but we will probably revamp how we handle alternate image formats to remove webp as a special case and just let web formats be extensible. I think that's a better point to add than to just add a bunch more if-else statements (we do have enough of those as it is).

**Comment by heynemann** [comment]
Definitely!!!

**Comment by Sinitra** [comment]
> @heynemann would you be open to my attempting such a refactor and opening it as a PR? I've written code for theatlantic.com that supports auto-webp, auto-avif, and auto-h265 (for animated gifs on safari). It's not open source, largely because it's such a hack. But the experience of extending thumbor to support it has made me pretty familiar with the auto-convert code, and has given me an understanding of where the pain-points are.

share your code, let's taste it

**Comment by markatli** [comment]
@heynemann Would love to see it as well! Thank you!

**Comment by fdintino** [comment]
Posting a comment to keep this issue open.

**Comment by Sinitra** [comment]
> Posting a comment to keep this issue open.

+1

**Comment by beeremy** [comment]
+1

**Comment by schappim** [comment]
+1

**Comment by acusti** [comment]
just wanted to mention that macOS Ventura and iOS 16 have added support for AVIF. this means Safari 16 will support AVIF on latest macOS and iOS, which is gonna bump global browser support ([currently 71%](https://caniuse.com/avif)) to well over 80%. i think this makes support for AVIF pretty critical and only increasing in importance from here forward.

**Comment by cortopy** [comment]
commenting to keep active

**Comment by fdintino** [comment]
I've opened #1476 to add AVIF encoding. It doesn't have any auto-avif features, but once AVIF encoding is generally supported that might be a good test case for the plugin proposal in #1446

**Comment by EgoistDeveloper** [comment]
I think this issue need be keep open.

**Comment by schappim** [comment]
bump

**Comment by acusti** [comment]
pretty cool to see the stale bot resulting in a PR being revived! https://github.com/thumbor/thumbor/pull/1476#issuecomment-1280753828

**Comment by RaphaelVRossi** [comment]
You can now use this feature here [Release 7.2.0](https://github.com/thumbor/thumbor/releases/tag/7.2.0)

Thank you @fdintino 🚀

**Comment by frasko23** [comment]
cool!
So one question does this soluction fit into Google images since avif format it is not supported directly by googlei mages..?

So i guess there should be a dynamic thumbor response to serve webp/jpeg/gif  to google image bot?

Or is possible in frontend a way to fit in html the fallback in
https://codelabs.developers.google.com/codelabs/avif#4

?
