### ISSUE TITLE
Security Key data storage

### ISSUE THREAD

**Issue by marblerun** [thumbor/thumbor#1361]
Simple question

What is the expected behaviour regarding the security key w.r.t local storage of images transferred from S3.

I have an almost 1:1 correspondence of image-name:image-name.txt, where each image-name.txt file contains the same value.

Not wishing to spell it out, but I suspect its obvious what this is.

I've always thought this was a little strange, given that there is a reasonable secure config file with the data contained within.

Is there a config option that prevents this from happening.

Kind regards,

Mike

**Comment by heynemann** [comment]
The reason for this Mike is to allow you to change your security key in the event it gets lost (someone has access to it). If we didn't store the security key in the storage, there would be no way to validate your previously generated images (meaning everything previous to rotating the key is lost forever). Does that make sense to you?

Anyway, this is the config to disable it -> STORES_CRYPTO_KEY_FOR_EACH_IMAGE

Just set it to false. There's a section on it in the docs [here](https://thumbor.readthedocs.io/en/latest/configuration.html)

From the docs:

```
If this flag is set to False, it essentially means that whenever you change the security key, 
for whatever reason, you just invalidated every single image that’s been generated before.

That may be ok if you have another service fetching stored images instead of allowing 
thumbor to do it (as many of thumbor users do).
```

**Comment by marblerun** [comment]
Actually no, it does not make any sense. Even in my small 2 server setup, that results in 0.5 M files with identical content, which seems very inefficient.                     

If you wanted to be ultra cautious, then perhaps 1 copy of the key in each of the 256 directories, but not 1 per image. 

I am totally no expert here, but it just feels like there must be a better way of doing this. 

And can I confirm that setting the config value to false has no effect on serving an image unless the security key is altered.

Our main image store is S3, so I have no issue with recreating from scratch if necessary.

Thanks

**Comment by heynemann** [comment]
I can see things from your point of view, but look at it from thumbor's:

* We provide a storage abstraction with a FileSystem implementation.
* This abstraction does not know anything about how you are going to recycle your security key.
* Because of that, the only secure way of handling key storage is storing atomically every file's security key. That way in the future we can definitely generate again using the file's URL if needed.

This is why thumbor provides all this extensibility points. With the knowledge you have of your use-case you can easily implement a storage that stores the key based on a timestamp (security-key-dec-2021.txt) as an example. That would allow you to change keys every beginning of month, or even go further and have a daily, or allow more than a key every day, or even have the file be a list of keys per month, instead of a single one. If the latter is what you decide, you need to implement a key validation URL Handler into thumbor in order to understand more than one key.

I recognize that this is a wasteful use of resources. But we are making no assumptions as to how you want to do it.

That said, I have an idea on how to improve this without losing our generic nature. I'll let you know how it pans out.

One last thing, if you change the configuration the text files keep being generated? That's not what's supposed to happen. If that's the case it's a bug.

Once again, sorry for the inconvenience this is creating!

**Comment by marblerun** [comment]
Hi Bernardo,

Don't worry, changing the config does stop the txt file from being generated.

Going back to a few points, given that we have our main storage in S3, we have actually never changed the security key. In fact, given that they sit behind an AWS ALB, the keys are in fact common, or I suspect we would have chaos.

I'm working on another issue which has reminded me of one the reasons this topic was raised in the first instance. I have been trying to capture what is now being called observability data, to show for instance how using thumbor in an image processing system would speed up tests like PageSpeed. Running such tests should show significant speed increases on the second and third run, or on a repeated test, given we have a load balancer in the path.

The first step would be to trace the images transferred from S3, but here we run into an issue with supervisord, as it never seems to record anything but stderr. It was while trying to tie in file creation in the Storage system with S3 access logs that this issue with txt files became apparent.

I've discovered a more detailed use of supervisord in a monitoring app called PMM2 from Percona, which I think is doing rather more than it should, but will see if I can compare diffs to see why no stdout info is generated for thumbor. If you have any tips, it would be welcome. Meanwhile, this can be can be closed shortly.

Many thanks

Mike
