### ISSUE TITLE
Which branch for features?

### ISSUE THREAD

**Issue by mpdude** [thumbor/thumbor#1371]
Given that 7.0.0 is currently alpha-only, seems to be a major upgrade hurdle and that the last 6.7.5 has been cut _after_ it, I wonder:

What is the right branch for new feature PRs?

Will features be accepted for 6.x and then merged into 7.x (`master`)? 

Apologies if this is answered somewhere, but at least I did not find this information.

**Comment by heynemann** [comment]
I'd say at this point, it depends. If it is a feature that improves severely thumbor's usage I'd say to backport to 6.x. Otherwise let's just move forward with 7. I've created a new AWS extensions project just for thumbor 7 (https://github.com/thumbor/thumbor-aws). Hopefully that will help a lot of people.

**Comment by heynemann** [comment]
I answered this in #1388. Closing here.
