### ISSUE TITLE
pyexiv2 instead of py3exiv2

### ISSUE THREAD

**Issue by heynemann** [thumbor/thumbor#1403]
Can we switch from py3exiv2 to pyexiv2? Much easier to install as it does not depend on boost. Seems to provide similar functionality.

**Comment by heynemann** [comment]
Tests are passing in #1404

**Comment by heynemann** [comment]
@kkopachev what do you think?

**Comment by mvhirsch** [comment]
Currently `thumbor-doctor` is checking for `pyexiv2` instead of `pyexiv3`: https://github.com/thumbor/thumbor/blob/a0a1338d328d6c0ecbd9eeaf510882313dca2764/thumbor/doctor.py#L279

Also as mentioned in PR https://github.com/thumbor/thumbor/pull/1404#issuecomment-1026057673 about docs this should finally be streamlined :grin:
