### ISSUE TITLE
How does STORAGE_EXPIRATION_SECONDS works ? 

### ISSUE THREAD

**Issue by neuraload** [thumbor/thumbor#1424]
Hello,

I have set STORAGE_EXPIRATION_SECONDS to one week and I am expecting thumbor to delete the older files under /tmp folder which is not happening. I guess I will have to delete them manually but I don't know if this is the way to do it. I am missing something ? Thank you.

Btw, using default storage option.

Best regards,

**Comment by heynemann** [comment]
Thumbor will not delete the older files. It will simply consider them as expired in disk and then download them again on the next request. It is not feasible for thumbor to perform cleanup of expired files in your filesystem, because every single thumbor user's filesystem is different. There are people storing files in Redis, S3, Mongo, NFS, ... You name it. Therefore thumbor asks the storage provider for the mtime for the file (whatever that is in your storage) and uses that to decide whether to download a new version or reuse what's in storage.
