### ISSUE TITLE
How to install py3exiv2 inside alpine linux

### ISSUE THREAD

**Issue by beeyev** [thumbor/thumbor#1432]
Hello, 
I am using Thumbor v7 inside alpine docker container.
Everything works fine except one thing. I can not install the package `py3exiv2` which is needed for EXIF metadata.

Could someone please help me find the way how to install it ?
I use this docker base image: `python:3.7-alpine`

**Comment by scorphus** [comment]
Hey 👋

What have you tried so far?

**Comment by RaphaelVRossi** [comment]
Hey @beeyev 

I was able to install `py3exiv2` on docker image `python:3.9-alpine`, because the package `boost-dev-1.77.0` install only python 3.9 lib version.

If you try to install on docker image `python:3.7-alpine` you will receive the following error:

```sh
/usr/lib/gcc/aarch64-alpine-linux-musl/10.3.1/../../../../aarch64-alpine-linux-musl/bin/ld: cannot find -lboost_python37
      collect2: error: ld returned 1 exit status
      error: command 'g++' failed with exit status 1
      [end of output]
```

Inside `/usr/lib` you can see only python 3.9 libs

```sh
/ # ls /usr/lib | grep python
libboost_python39.so
libboost_python39.so.1.77.0
libpython3.9.so.1.0
libpython3.so
python3.9
/ # 
```


To install `py3exiv2` , you need to install these following alpine packages first:

```sh
apk update && apk add boost-dev exiv2 exiv2-dev build-base

pip3 install py3exiv2
```

**Comment by scorphus** [comment]
Cool! Glad it works. I'm closing this one.

BTW, in case you need to stick to `python:3.7-alpine`, you can create a copy of (or a link to) the shared object file:

    ln -s /usr/lib/libboost_python39.so /usr/lib/libboost_python37.so
