### ISSUE TITLE
Avif and autorotation not working properly

### ISSUE THREAD

**Issue by OndrejIT** [thumbor/thumbor#1557]
When using avif, thumbor does not respect rotation of the photo according to the exif.
If I use jpg or webp, the photo will rotate correctly

Sample photo: https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_4.jpg

```
thumbor==7.4.7
thumbor-aws==0.6.0
pillow-avif-plugin==1.3.1
https://github.com/OndrejIT/thumbor-crypto/archive/devel.tar.gz
pycurl==7.45.2
CairoSVG==2.6.0
sentry-sdk==1.17.0

```

**Comment by luzfcb** [comment]
Up

**Comment by scorphus** [comment]
EXIF data is being preserved for AVIF. Any ideas, @fdintino?

**Comment by scorphus** [comment]
Pinging @fdintino again, just in case.

**Comment by fdintino** [comment]
Sorry for the delay in responding here. It looks like this is a bug in pillow-avif-plugin itself. The AVIF image spec dictates that orientation info in exif metadata should be ignored, and so when converting from another image format with exif orientation it's necessary to set the `irot` transform flag on the image.

I'll look into fixing this in pillow-avif-plugin. In the meantime, it looks like this can be worked around by enabling the `RESPECT_ORIENTATION` setting in thumbor.

**Comment by fdintino** [comment]
This is fixed in pillow-avif-plugin 1.4.2.

**Comment by scorphus** [comment]
> This is fixed in pillow-avif-plugin 1.4.2.

I _still_ reproduce this issue with `pillow-avif-plugin>=1.4.1` (i.e. versions `1.4.1`, `1.4.2` and `1.4.3`)

To _my_ understanding, this has to do with implementation of AVIF support _in Thumbor_ rather than with pillow-avif-plugin:

> [EXIF data is being preserved for AVIF. Any ideas, @fdintino?](#issuecomment-1602054239)

I'm probably missing something. @fdintino would you kindly share why you believe pillow-avif-plugin 1.4.2 fixes this issue? Thanks!

**Comment by fdintino** [comment]
I explained why the exif orientation wasn't working in [this comment](https://github.com/thumbor/thumbor/issues/1557#issuecomment-1842038614) above:

> The AVIF image spec dictates that orientation info in exif metadata should be ignored, and so when converting from another image format with exif orientation it's necessary to set the irot transform flag on the image.

So it's an issue with the way AVIF images are decoded and displayed, not with thumbor.

This was fixed in https://github.com/fdintino/pillow-avif-plugin/pull/40. I detect the EXIF orientation—if present—and convert that into the appropriate AVIF transform flags. That was part of the pillow-avif-plugin 1.4.2 release.

Since you're still seeing the problem, I was curious whether it's an issue with the AVIF decoder in one of the browsers. [Visit this page](https://zpl.fi/exif-orientation-in-different-formats/#avif) to see how your browser treats imir and irot vs exif for AVIF images. On my machine, it looks like Firefox and Safari exhibit the correct behavior, while Safari ignores both EXIF orientation and the imir/irot flags. If you're seeing the same thing, I think the only solution is to enable the `RESPECT_ORIENTATION` setting in thumbor.

**Comment by scorphus** [comment]
So, it seems like we have different interpretations of this issue.

Regardless of which pillow-avif-plugin version is used — `1.4.1`, `1.4.2` or `1.4.3` — I always see the word "top" at the top. For both Firefox and Chrome.

What I perceive, though, is something else. Which I think I can hopefully try and do a better job at expressing myself below. 😊

First, please, make sure you have these in your `thumbor.conf`:
    AUTO_AVIF = True
    PRESERVE_EXIF_INFO = False

I used pillow-avif-plugin 1.4.1:

    »»»» pip install -U pillow-avif-plugin\<1.4.2
    Requirement already satisfied: pillow-avif-plugin<1.4.2 in /Users/scorphus/.../python3.11/site-packages (1.4.1)

Then compare the following different URIs.

> http://0.0.0.0:8888/unsafe/https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_4.jpg
![image](https://github.com/thumbor/thumbor/assets/2112697/ad5a89c6-1cfd-4e04-bda2-e2ff306e9bb1)

> http://0.0.0.0:8888/unsafe/filters:format(jpg)/https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_4.jpg
![image](https://github.com/thumbor/thumbor/assets/2112697/7cfd8a50-a269-40dd-a024-1b92a86a1e10)

> http://0.0.0.0:8888/unsafe/filters:format(avif)/https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_4.jpg
![image](https://github.com/thumbor/thumbor/assets/2112697/ae02828c-4d01-437b-aeb6-85b4bafa3c6c)

> http://0.0.0.0:8888/unsafe/filters:format(webp)/https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Landscape_4.jpg
![image](https://github.com/thumbor/thumbor/assets/2112697/c46fc328-8ca0-4f50-8aea-538d4164a7da)

Hence:
> [EXIF data is being preserved for AVIF. Any ideas, @fdintino?](#issuecomment-1602054239)

These are, therefore, different issues — seemingly though, as I cannot reproduce what you described and am surely missing something.

I'm more than happy to provide more details. Also more than happy to follow your hints regarding what I'm missing.

Thanks!

**Comment by fdintino** [comment]
Just to rule one thing out: is your local thumbor running with a result storage? If so, could you switch it to `no_storage`?

**Comment by scorphus** [comment]
Those are `unsafe` URIs and `thumbor.conf` has it `False` for storing unsafe.

I should have added this to my previous message, sorry:

> `git diff -- thumbor/thumbor.conf | tee | pbcopy`
```diff
diff --git a/thumbor/thumbor.conf b/thumbor/thumbor.conf
index 8a904e92..5166ae63 100644
--- a/thumbor/thumbor.conf
+++ b/thumbor/thumbor.conf
@@ -41,6 +41,7 @@ home = expanduser("~")
 ## Automatically converts images to Avif if Accepts header present and
 ## pillow-avif-plugin is enabled
 # AUTO_AVIF = False
+AUTO_AVIF = True
 
 ## Automatically converts images to Heif if Accepts header present and
 ## pillow-heif is enabled
```

**Comment by fdintino** [comment]
I think I understand. So, to briefly summarize: you're seeing exif information being retained, despite `PRESERVE_EXIF_INFO = False`. That is indeed a bug in pillow-avif-plugin; I can see the line that's causing it. However, the originally reported issue was that orientation from EXIF data was not carrying over and affecting the rotation when images were saved as AVIF. What you're describing is related, but is actually the opposite: that the orientation is persisting (and so, the EXIF info is) despite the fact you've instructed thumbor _not_ to preserve it. Have I got that correct?

**Comment by scorphus** [comment]
> When using avif, thumbor does not respect rotation of the photo according to the exif. If I use jpg or webp, the photo will rotate correctly
> --->8---

Considering what you wrote, and considering what I can and cannot reproduce, we likely have different interpretations of that original report 👆 And I am more than convinced that I am missing something 😁

The original report contains no expected behavior other than "it should rotate in the same way as jpg or webp" — which is considered to be the correct behavior. That is what I can see/reproduce. IOW: [EXIF data is being preserved for AVIF](#issuecomment-1602054239). [This comment](https://github.com/thumbor/thumbor/issues/1557#issuecomment-1943254765) has all I can (or cannot) reproduce and the steps to do so.

Do you or anyone else have an idea of what I am missing? Do you see anything different? Do things behave differently than [what I previously described](https://github.com/thumbor/thumbor/issues/1557#issuecomment-1943254765)? What are the steps I should take to reproduce what you see?

@OndrejIT hopefully you're able/willing to chime in and share what you would expect. It would be helpful to have an image representation of your expectation along with the relevant configuration entries.

Apologies if I'm still not clear in my statement 😊

**Comment by fdintino** [comment]
I seem to be unable to reproduce the issue myself, but I was at one point. I think this may be the result of changes to how browsers handle EXIF transformations for AVIF images. As recently as December 15, 2021, [a bug report for Chrome that exif transforms aren't applied to AVIF images](https://issues.chromium.org/issues/40197587) was closed as WONTFIX, citing the image format specifications. I don't have the contents of that spec, but MIAF 7.3.10 gets quoted in these discussions; reproducing the excerpt:

> There should be no image transformations expressed by Exif (rotation, mirroring, etc.) indicated in the Exif metadata, in files encoded according to this document. If present, they shall be ignored by a MIAF renderer, i.e. not cause a change in the presentation of associated images by a MIAF player.

These transformations are instead meant to come from the imir and irot transform flags of the image.

At some point since then, the Chromium developers must have had a change of heart, because it appears that EXIF transformations do in fact work for AVIF images, even in the absence of transform flags. I cannot find anything in the changelogs or issues to say when this occurred, which would tell me how that fits into the timeline of this issue being opened.

My understanding of the issue (based on my earlier reproduction) is that the reporter was viewing images in an application or browser that exclusively supported imir and irot. Or they were using a version of Safari that supports neither (I know that it was unsupported as late as Safari 17.3). The issue for the former situation is fixed in pillow-avif-plugin 1.4.2. There isn't a solution to the latter issue aside from requiring newer Safari or enabling RESPECT_ORIENTATION.

On the basis of all that, I think it's fair to say that this issue can be closed.

**Comment by OndrejIT** [comment]
@fdintino @scorphus I'm sorry I didn't write back.
My setup and intent is to make a JPG photo that has exif rotation into an avif photo that is hard rotated and has no original exif. Thus the thumbor setting:

```
AUTO_AVIF = True
RESPECT_ORIENTATION = True
PRESERVE_EXIF_INFO = False
```

So thumbor should rotate the photo according to the exif and not insert the exif in the resulting rotated photo, but this doesn't happen with avif, the photo is rotated as the original jpg if I don't respect the exif. If I set PRESERVE_EXIF_INFO = True, firefox displays the photo correctly, but this is not a solution for me. For one thing, browsers can rotate photos badly, see comments here, and I don't want sensitive exif data (GPS etc..)

**Comment by OndrejIT** [comment]
On further investigation I found that PRESERVE_EXIF_INFO = False does not work correctly. Even if the value is False, the exif information (including orientation) remains in the photo.

Furthermore, the orientation and physical rotation of the photo is different.

> AUTO_AVIF = True
> RESPECT_ORIENTATION = True
> PRESERVE_EXIF_INFO = False
> Exif:
> ...
> Orientation : Rotate 270 CW
>  ...
> The photo is displayed incorrectly, is physically rotated incorrectly, and contains metadata when it shouldn't.

---

> AUTO_AVIF = True
> RESPECT_ORIENTATION = True
> PRESERVE_EXIF_INFO = True
> Exif:
> ...
> Orientation : Horizontal (normal)
> ...
> The photo displays well, it is also physically well rotated.


I'm still seeing if I can fix this. But please open an issue @heynemann thank you.
