### ISSUE TITLE
Search Engine Friendly URLs

### ISSUE THREAD

**Issue by f00bar** [thumbor/thumbor#217]
Hello,

Is there an easy way to generate SEO friendly image URLs? We started using Thumbor but our images are no longer being pulled by the google crawler. 

We're not using url-based filters but we're using the crop feature in the url so I think the main issue is this pattern - 0x0:537x338 - specifically the colon character.

Thanks!

**Comment by gabriel-kaam** [comment]
Hey guys , I know this thread is closed ; but do we have a fix for that ?

**Comment by heynemann** [comment]
Not really @gabriel-kaam. Changing thumbor's url structure is super hard due to breaking every single image out there. Or we'd have to support both (we did that a number of times and it creates problems).

**Comment by gabriel-kaam** [comment]
Got it ; thanks for the update @heynemann .

In some thread I've read people talking about create a custom HTTP loader ; wdyt ?

I was thinking of doing something like this: instead of having the path to original image in the url ; I would pass it a base64 string . This way, my thumbor url would be SEO-friend (Google does not seem like the semi colon in it), while minimizing the overhead of the whole operation (encoding and decoding a base64 should be pretty fast),

What do you think of that that solution ?

Ex: instead of having this : https://thumbor-2.modalova.fr/unsafe/0x500/https%3A%2F%2Fcdn.shopify.com%2Fs%2Ffiles%2F1%2F0275%2F6925%2F8630%2Fproducts%2FDeserto-modelo.jpg%3Fv%3D1625499024

We would have something like  : https://thumbor-2.modalova.fr/unsafe/0x500/aHR0cHM6Ly9jZG4uc2hvcGlmeS5jb20vcy9maWxlcy8xLzAyNzUvNjkyNS84NjMwL3Byb2R1Y3RzL0Rlc2VydG8tbW9kZWxvLmpwZz92PTE2MjU0OTkwMjQ=

**aHR0cHM6Ly9jZG4uc2hvcGlmeS5jb20vcy9maWxlcy8xLzAyNzUvNjkyNS84NjMwL3Byb2R1Y3RzL0Rlc2VydG8tbW9kZWxvLmpwZz92PTE2MjU0OTkwMjQ=**
is
https://cdn.shopify.com/s/files/1/0275/6925/8630/products/Deserto-modelo.jpg?v=1625499024
base64 encoded .

**Point 2**

Is that work ; I was thinking it would be great to also add a new part to the url (that could be ignored) , just to make the url more seo-friendly like https://thumbor-2.modalova.fr/unsafe/0x500/aHR0cHM6Ly9jZG4uc2hvcGlmeS5jb20vcy9maWxlcy8xLzAyNzUvNjkyNS84NjMwL3Byb2R1Y3RzL0Rlc2VydG8tbW9kZWxvLmpwZz92PTE2MjU0OTkwMjQ=/name-of-my-image.jpg

Wdyt ?

I'm not really good a python and not familiar with the Thumbor API ; but do you think that would be possible using a custom HTTP Loader ? If so ; do you have a link to documentation or working examples that I could use ?

And what do you think of my second point ?

Thanks
