### ISSUE TITLE
PNG/GIF Quality control support

### ISSUE THREAD

**Issue by prmdsharma** [thumbor/thumbor#221]
Hi,

Currently quality filter ignores the png/gif images. Can you please suggest some way to achieve that. We need the this support urgently, if some code code changed is required , I am ready for that.

thanks
Pramod

**Comment by lyrixx** [comment]
Hello.

I would like to reopen this issue. There are many service that are able to optimize PNG.
For example on https://tinyjpg.com/ I'm able to compress by 74% [an image
](https://user-images.githubusercontent.com/408368/28633812-4be08f68-7235-11e7-8e6f-117dd43f5c54.png)

What do you think of this?

**Comment by rfloriano** [comment]
Hello @lyrixx.

As clearly explained by @dhardy92, PNG format is a lossless, quality is not relevant.
We've same problema in globo.com, many of (big) images are PNG.
In browsers that support WebP, it is not a problem, because we turned on `AUTO_WEBP`.
However, for other browsers it is a problem.

Our cases, we have many PNG images that has no alpha layer, so we could change it to a JPG and delivery it. JPG has a quality param and engines like PIL can compress these images.

I have start a [branch](/thumbor/thumbor/tree/auto-png-to-jpg) with an idea to solve this: Create an `AUTO_PNG_TO_JPG` flag and auto change PNG format to JPG when it has no transparency pixels.
It would solve your problem?

**Comment by kkopachev** [comment]
we're using filter for that purpose:

```python
#!/usr/bin/python
# -*- coding: utf-8 -*-

from thumbor.filters import BaseFilter, filter_method
from thumbor.utils import logger


def is_webp(context):
    return (context.config.AUTO_WEBP and
            context.request.accepts_webp and
            not context.request.engine.is_multiple() and
            context.request.engine.can_convert_to_webp())


class Filter(BaseFilter):
    @filter_method()
    def format_auto(self):
        if is_webp(self.context):
            self.context.request.format = 'webp'
            logger.debug('Webp is supported, using webp')
        elif not self.context.request.engine.is_multiple():
            self.context.request.format = 'jpg'
            logger.debug('Webp is not supported, using jpg')
```

additionally, there is a plugin optimizer to do similar thing https://github.com/thumbor/thumbor-plugins/blob/master/thumbor_plugins/optimizers/auto.py

**Comment by lyrixx** [comment]
Hi. 

thank for theses fast replies ;)

Actually, I'm quite new with image processing and thumbor. And I don't understand how service like  https://tinyjpg.com/  are able to reduce the size of a PNG picture. I tested it and the format is sill PNG after the "compression".

I would like to be able to keep the same format, but with a lower size. Do you know how I can achieve that?

Thanks.

**Comment by kkopachev** [comment]
In that case there are few optimizers available for thumbor. They all use cli tools.

https://github.com/thumbor/thumbor-plugins/blob/master/thumbor_plugins/optimizers/pngquant.py
https://github.com/thumbor/thumbor-plugins/blob/master/thumbor_plugins/optimizers/pngcrush.py
https://github.com/thumbor/thumbor-plugins/blob/master/thumbor_plugins/optimizers/optipng.py

You could also find a lot of compression tools described here https://css-ig.net/png-tools-overview

**Comment by lyrixx** [comment]
Thanks a lot.
