### ISSUE TITLE
Using Upload and File Loader

### ISSUE THREAD

**Issue by pfuhrmann** [thumbor/thumbor#249]
Hi, thanks for this great tool!

I am trying to use upload together with file loader but I don't understand how to access file from the URL like example.com/image/sd54asdasdf55/image.jpg as it is somehow magically mapped to directory hash like 1a/aa15somehashsdf.

Not sure if my question is clear.

**Comment by ysadiq** [comment]
@heynemann me too, i'm confused about the hash thing

for example i posted my image with slug as shown below

```
curl -X POST "localhost/image" \
     -H "Slug: testimage.png" \
     --data-binary "@/Users/YSaddiq/Desktop/Screen Shot 2015-01-19 at 10.36.48 AM.png" \
     -m 300 \
     -v \

```

and this the response i got

```
HTTP/1.1 201 Created
Date: Wed, 21 Jan 2015 13:58:45 GMT
Content-Length: 0
Content-Type: text/html; charset=UTF-8
Location: /image/7f56856de9c7480ca7e99e7a0a12ec75/testimage.png
Server: TornadoServer/3.2.1
```
The url is working fine, the problem is the image file is stored in a CAS  mechanism (which is awesome) FILE_STORAGE_ROOT_PATH/c1/0d81aa453ff68241e764efcf0f68becdd2e71f

but how can i retrieve the image programatically if the only thing i have is the location of the image which is returned in the header response?

thanks

**Comment by pfuhrmann** [comment]
@ysadiq this was exact same problem I have been having. It looks like it was not created with using both upload and file loader together. Workaround would be to use URL of image twice. i.e. inside loader URL insert uploaded URL, which is stupid really.
