### ISSUE TITLE
PPA not updated

### ISSUE THREAD

**Issue by runa** [thumbor/thumbor#325]
Heyas :) 

Are you planning to update [the PPA](https://launchpad.net/~thumbor/+archive/ubuntu/ppa) or I should install thumbor from another source?

Thanks!

**Comment by stephenmuss** [comment]
To date there is still no PPA for trusty or utopic. I've also tried raising this issue through launchpad.

**Comment by heynemann** [comment]
I'm not sure what to do to address this... Anyone want to be our maintainer for the PPA?

**Comment by marcelometal** [comment]
Sorry for the late reply. My intention is to upload it to debian unstable, so I'm working to fix many errors and warnings.  This is my branch https://github.com/marcelometal/thumbor/commits/debian. Soon I will submit a pull request. Cheers!

Errors and warnings list:

* W: thumbor source: source-nmu-has-incorrect-version-number 3.7.1
* W: thumbor source: ancient-standards-version 3.9.3 (current is 3.9.6)
* W: thumbor: image-file-in-usr-lib usr/lib/python2.7/dist-packages/thumbor/integration_tests/imgs/alerta.gif
* W: thumbor: image-file-in-usr-lib usr/lib/python2.7/dist-packages/thumbor/integration_tests/imgs/brasil_45.png
* W: thumbor: image-file-in-usr-lib usr/lib/python2.7/dist-packages/thumbor/integration_tests/imgs/cmyk.jpg
* W: thumbor: image-file-in-usr-lib usr/lib/python2.7/dist-packages/thumbor/integration_tests/imgs/dilmahaddad.jpg
* W: thumbor: image-file-in-usr-lib usr/lib/python2.7/dist-packages/thumbor/integration_tests/imgs/frame.9.png
* W: thumbor: image-file-in-usr-lib usr/lib/python2.7/dist-packages/thumbor/integration_tests/imgs/logo-FV.png-menor.png
* W: thumbor: image-file-in-usr-lib usr/lib/python2.7/dist-packages/thumbor/integration_tests/imgs/tumblr_m9u52mZMgk1qz99y7o1_400.gif
E: thumbor: duplicate-updaterc.d-calls-in-postrm thumbor
* W: thumbor: binary-without-manpage usr/bin/thumbor
* W: thumbor: binary-without-manpage usr/bin/thumbor-config
* W: thumbor: binary-without-manpage usr/bin/thumbor-url
* E: thumbor: python-script-but-no-python-dep usr/bin/thumbor
* E: thumbor: python-script-but-no-python-dep usr/bin/thumbor-config
* E: thumbor: python-script-but-no-python-dep usr/bin/thumbor-url
* N: 1 tag overridden (1 warning)

**Comment by mpdude** [comment]
@guilhermef Closing this issue means the PPA won't be updated anymore? 

Maybe the docs (https://github.com/thumbor/thumbor/wiki/Installing) should then mention that installing through `apt` is discouraged?

**Comment by guilhermef** [comment]
@marcelometal can you update the PPA ?

**Comment by mpdude** [comment]
Isn't the point of PPA that it automatically builds the releases? 

If not, could you document the necessary steps somewhere so others can do the grunt work?

**Comment by marcelometal** [comment]
@guilhermef  I know, I am in debt... Yesterday, I took it back and soon I will send Thumbor package to Debian/Ubuntu. Believe me! ;)

**Comment by mpdude** [comment]
If I can support you let me know!

**Comment by gi11es** [comment]
FYI, I've picked up the task of packaging Thumbor for Debian. I needed to do it for our internal purposes of getting Thumbor into production and I figured I might as well attempt to do it up to Debian's standards and get it there for everyone else to enjoy.

I've been in touch with @marcelometal. @filippog and Moritz Mühlenhoff who are fellow Wikimedia Foundation employees and Debian developers have offered to help me through the process to get all of that work into Debian proper.

I've made a Debian wiki page to track the dependency tree and progress on packaging: https://wiki.debian.org/Python/Thumbor

And I've put all my packaging work (backports, version updates and brand new packages) here: https://github.com/gi11es/thumbor-debian

I've just completed packaging all the dependencies for Debian sid (both runtime and test dependencies). I will backport the brand new packages to jessie-backports once they've been uploaded. Now I'm going to try to package Thumbor 6.0.1 itself. I might start from scratch instead of using what's currently in Thumbor's debian folder, as it's based on a very ancient version of Thumbor. I intend to store the packaging work itself on Debian's git repos eventually anyway, and not as part of Thumbor's own checkout.

You can follow all that work there if you're curious: https://phabricator.wikimedia.org/T134485

**Comment by heynemann** [comment]
Awesome job Gilles!!! Thank you so much for your efforts!

**Comment by mpdude** [comment]
@gi11es awesome job!

**Comment by gi11es** [comment]
Getting Thumbor into Debian is really close, now that #776 has been merged. Accepting these two PRs would make the package slightly cleaner: #762 #761 

But more importantly, it would be nice if you guys can issue a new major release (6.1.0, I presume) that includes #727 (and ideally, my two open PRs mentioned above).

This way we can truly use the version package as obtained from https://github.com/thumbor/thumbor/tags and not the latest master, to include as the Debian source package.

FYI the Debian build phase should be able to run most tests. In the initial release we might skip a handful of tests for optional features (sentry, remotecv) just because packaging these optional dependencies and their sub-dependencies is low priority on the Debian side. It'll get done eventually and we'll update the Debian package when those tests can be run again in the context of the Debian package build (there's nothing stopping people from running those tests after installing Thumbor via its Debian package and raven/remotecv via pip, for example).

**Comment by gi11es** [comment]
Thumbor has just been uploaded to Debian unstable: https://ftp-master.debian.org/new/thumbor_6.3.2-1.html

**Comment by heynemann** [comment]
VERY GOOD JOB GUYS!!!!

**Comment by marcelometal** [comment]
Great news, Thumbor was accepted into Debian unstable \m/
https://packages.debian.org/sid/thumbor
