### ISSUE TITLE
Handling '+' in path

### ISSUE THREAD

**Issue by atiro** [thumbor/thumbor#463]
There seems to be an inconsistency between how '+' characters are handled for secure URLs, which means the generated URL is treated as malformed. The CryptoURL function seems to treat them as valid characters in the path (which they are) and generates a hash based on this, but when the request comes in to the Imaging Handler it calls Url.encode_url on them, which doesn't consider '+' as safe so converts it to '%2B'; the hash generated from that is different and so the request is rejected.

Easy fix is to encode the url in the same manner (urllib.quote) before passing it to CryptoURL and use that encoded URL from that point on.

**Comment by heynemann** [comment]
I'm not sure I understand. Is this an issue with thumbor or with the way libthumbor is generating URLs?

**Comment by pippoppo** [comment]
Hi,
maybe I have a similar problem, I'm just beginning to investigate. I'm reporting here, and will be back again with a solution as soon as possible (hopefully).

This is my unsafe url:
http://www.gelestatic.it/thimg/unsafe/50x50/smart/http://iltirreno.gelocal.it/polopoly_fs/1.11139912!/httpImage/image.jpg_gen/derivatives/gallery_978/image.jpg

then I calculate the hmac and its base64 this way (in php):
echo hash_hmac('sha1', '50x50/smart/http://iltirreno.gelocal.it/polopoly_fs/1.11139912!/httpImage/image.jpg_gen/derivatives/gallery_978/image.jpg', 'mykey', true);

and with "php myscript.php | base64" i obtain this
uDyiwTS86GVmrfEUlZdmiAiMdNE=
so that I can produce the final url

http://www.gelestatic.it/thimg/uDyiwTS86GVmrfEUlZdmiAiMdNE=/50x50/smart/http://iltirreno.gelocal.it/polopoly_fs/1.11139912!/httpImage/image.jpg_gen/derivatives/gallery_978/image.jpg

that doesn't work

hope it's clear, and maybe I have the same problem (esclamation mark instead of plus sign)

Best,
corrado

**Comment by pippoppo** [comment]
same effect using
strtr( base64_encode($signature), '/+', '_-');
like phumbor php library does, that is equivalent to base64.urlsafe_b64encode in python

**Comment by pippoppo** [comment]
Ok, I've got it.
It works when I substitute the ! char with the corresponding %21 before applying the hash_hmac.
Now the generated url correctly works:
http://www.gelestatic.it/thimg/smfg7o9nP4Or8dfxtcLScUfruxo=/50x50/smart/http://iltirreno.gelocal.it/polopoly_fs/1.11139912!/httpImage/image.jpg_gen/derivatives/gallery_978/image.jpg

**Comment by heynemann** [comment]
Can you supply a patch for the phumbor library?

Bernardo Heynemann
Developer @ globo.com

**Comment by pippoppo** [comment]
Hi Bernardo, (and thanks a lot for thumbor)
yes, I'll arrange a patch for phumbor soon. Same "problem" with the django-thumborize python lib

Best,
corrado

**Comment by pippoppo** [comment]
Reading the old issues, I've found something possibly related:
https://github.com/thumbor/thumbor/issues/289
Maybe you could consider adding the "!" also to the encoded url chars? Makes sense?

**Comment by pippoppo** [comment]
I've tried to add the ! to the encoded url chars in url.py and it doesn't work (I'm not a pythonista so I could have done it wrong, fwiw). So at the moment I have  to urlencode clientside before applying the hash_hmac function.

sorry for the noise,
corrado
