### ISSUE TITLE
Add support Client Hints (DPR, Width, Resource-Width)

### ISSUE THREAD

**Issue by igrigorik** [thumbor/thumbor#549]
Chrome 46 is shipping with [support for Client Hints](https://www.chromestatus.com/feature/5504430086553600). Specifically, we'll send them on an opt-in basis and can advertise device DPR, viewport width, and resource display width (when it's known) to the server to enable automated delivery and optimization of responsive images.

For additional context on motivation and developer use cases, see: 
https://developers.google.com/web/updates/2015/09/automating-resource-selection-with-client-hints

It would be great to have CH support in thumbor! :)

**Comment by masom** [comment]
:+1: 

Have you considered how CDN would implement content caching for client hints? Right now most of them use the url as cache key.

Regardless of CDN suppoprt, this seems like a great feature to implement.

**Comment by igrigorik** [comment]
At a minimum the server (thumbor) should return a `Vary` header indicating which hints it used, which tells the upstream cache to use those as part of its cache key. For more details, see: 
http://tools.ietf.org/html/draft-grigorik-http-client-hints-03#section-2.2.2

Depending on the actual server or provider you use, you may also be able to customize how the cache key is computed to reduce fragmentation, etc.

**Comment by heynemann** [comment]
@igrigorik have any of you guys at google (that you know of) discussed the use of this type of Vary with any of the major CDNs (Akamai, Cloudfront, etc)?

I wonder when Amazon will support varying by this kind of thing. Right now this is what's in their docs:

    Content Negotiation
    The only acceptable value for the Vary header is Accept-Encoding. CloudFront ignores other values.

from http://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/RequestAndResponseBehaviorCustomOrigin.html#ResponseCustomContentNegotiation

I was wondering whether we would be able to help thumbor users with automatic detection (the same way we do with auto-webp).

**Comment by heynemann** [comment]
Apparently now you can vary by different headers in Cloudfront. Nice.

**Comment by igrigorik** [comment]
As you noted, CloudFront supports Vary: http://friism.com/webp-content-negotiation-cloudfront

AFAIK, Akamai does support Vary as well, and even allows you to customize the generated cache key via additional configuration. That said, I'll defer to @yoavweiss on this one :)

**Comment by colinbendell** [comment]
You are correct. On Akamai you can use the Vary header to specify a different forward origin server, change the path or add the value to the cache key.

**Comment by heynemann** [comment]
Does Google cloud also offer CDN support (I couldn't find in the docs doing a quick search)? If so, do you guys know if it supports this as well? I'm sorry I'm asking this many questions. Just trying to be thorough before we commit on implementing it... :)

**Comment by igrigorik** [comment]
@heynemann there isn't a single "Google CDN", there is: App Engine (sandboxed and managed VMs), compute engine with different load-balancing (TCP, HTTP, etc) configurations, cloud storage, etc.. Some of those configurations offer configurable edge caching, others don't. Now, that said, for cases where configurable edge caching is available.. yes, Vary should be supported.

**Comment by Perni1984** [comment]
@heynemann: Hi, do you have eventually any update on this. It would be highly interesting for a project I am currently working on.

**Comment by heynemann** [comment]
We need a specific use case to use Client Hints on. What do you have in mind @Perni1984 ?

**Comment by Bladrak** [comment]
@heynemann a first step could be to pass those values through to the loaders / storages, and retrieve an eventual DPR argument from them, plus return Vary headers if those are set?
Should this feature be optional as well?
Maybe in a second time we could think about handling those arguments to resize the images on the fly?

**Comment by heynemann** [comment]
That's the main issue here. We can do all those things, but I wonder what we are trying to achieve. I can think of a couple scenarios:

* Vary quality based on network;
* Vary image size based on DPI (retina images).

Both have issues around them. What I wanted to gauge from thumbor's committers is whether these are scenarios you'd like to use and if we have anyone willing to contribute this feature.

**Comment by Bladrak** [comment]
Regarding the quality varying based on the network, that's something we could start right away through the optimizers implementations I guess. I don't see much custom use cases there.
However, regarding the variation of image size based on the DPR, there's a lot of use cases possible. That's why I was thinking about first implementing the pass-through to loaders/storages, which would allow users to implement there own use cases if need be; and in a second time, offering an option to scale the image based on those args within thumbor.

I should have some time to work on that in the coming weeks. I'll try to gather real use cases scenario as well. But maybe we can begin to work on some things without those. What do you think?

**Comment by masom** [comment]
Given that imgix implemented Client Hints it is probably worth implementing.

The feature with the most impact would be knowing what sizes a device requests and returning images matching that. This would boost thumbor's adoption for mobile-first platforms.

One way to approach this is to develop a filter that will take in the raw url and apply the request size being requested.

To prevent DDOS, thumbor could expose a list of allowed image sizes ex: [ [100, 100], [200, 200], [250, 250], [300, 300] ] and select the most appropriate one based on the request hints.

**Comment by heynemann** [comment]
As long as we do not increase complexity significantly in thumbor's codebase, I'm all for it. I'm not being negative here, @Bladrak. I'm just very worried about thumbor's codebase as it is. We've had a LOT of work trying to keep it small and it's HUGE, lol.

I do think your approach is good, though. I'd start with just putting it into context. No need to pass it around explicitly. When the request starts, verify the headers and just append it to a context.request.client_hints dictionary.

The context is already accessible to almost anything in thumbor.

As for @masom suggestion, I don't think we should pass sizes. The way we see it, thumbor should calculated the size based on DPR. What this means is that, if an image is 300x300 for 1.0 DPR, it should be 600x600 for 2.0 DPR. The main issue here is how to crop "around" the original image, without including a part of the image that was not supposed to be there (an editor crops only Obama on a picture with him and Putin. We don't want the retina version to include Putin).

The quality variation, on the other hand, is A LOT simpler to implement and might be VERY important performance-wise. An user in edge that can get images smaller than 1kb probably will be very happy, even if the images are low quality.

Does that make sense?

**Comment by masom** [comment]
Yeah.

So how about this: 
- Implement a `DeviceHint` pre-filter that is automatically executed if enabled + headers are present.
- The filter itself will change the request to match the request within acceptable boundaries.
- If the filter cannot change anything the request stays the same.
- Device Hints would be opt-in through configuration.
- The original request would be used as fallback if the hints are not acceptable / missing.

**Comment by heynemann** [comment]
Why does it have to be a filter? We can add to [request processing](https://github.com/thumbor/thumbor/blob/master/thumbor/handlers/imaging.py#L45) the task of adding client hints to the request if they are available.

I don't see anything wrong with this. No need to be opt-in (won't add any significant burden to requests that do not have the headers).

If this PR won't include any USAGE of the client hints, I don't think we need to worry much. Usage of the client hints, though, is going to be opt-in, definitely.

What do you think?

**Comment by Bladrak** [comment]
There's also Response headers to be set (``Content-DPR`` and ``Vary`` for instance). Where should we handle those?

**Comment by heynemann** [comment]
The same place we do vary for auto webp.

**Comment by igrigorik** [comment]
Excited to see progress on this. A couple of quick notes, as I'm reading this...

- Chrome & Opera will be shipping support for `Save-Data: on` in early 2016 (see [blink-dev thread](https://groups.google.com/a/chromium.org/d/msg/blink-dev/-_pEwnE_e_Y/zx5KFs3VBAAJ)). I think this would be a *great* candidate for Thumbor.. It's an explicit signal that user has opted into a "data savings mode", and there many optimization strategies that could work here: always return 1x, apply higher compression, etc.
- Support for `DPR` hint will go a long way towards enabling dpr-aware `img` elements! E.g. the site does not have to specify sizes or anything else. Drop in thumbor, CH opt-in and you've got responsive images.
- Support for `Width` allows pixel-perfect delivery (or some approximation of it).

**Comment by sbaechler** [comment]
The client hints should be present in `context.request.headers`. So they should automatically be available in Thumbor.
@heynemann For Thumbor to be able to crop Hi-DPR images, the Transformer class needs to be dpr-aware as well. It should not be to hard to add that feature and if the default was 1, then it would be fully backwards compatible. 

Maybe it would make sense, to allow setting the dpr in the URL as well. Otherwise it might break websites that use art direction and depend on the thumbnail library deliver images based on CSS pixel and not absolute pixel values. In that case, DPR would have to be extracted and added to the context.request object. The target size can be passed in with client hints as well. Here you would have to define how the values are prioritized over the size passed via the URL.

**Comment by sbaechler** [comment]
I have a use case where I need the client hints in a filter. I think the easiest way to make them available is to add the whole request header to the `scope.request` object. The request headers is a Tornado object that behaves like a dictionary. So one can use `dpr = request.headers.get('Dpr')`.

An example adjustment is here:
https://github.com/sbaechler/thumbor/commit/9edf8291e0939d726bde8f12d2a79b1f09321d07

As @igrigorik pointed out, Thumbor would have to return a `Vary` header in the response. A possible way to implement this would be to add a `cache_vary` property to the context which is a Python set. So all filters or plugins that used one of the client hints could add its name to the set. In the end of the request cycle it gets serialized and added to the response header.

**Comment by heynemann** [comment]
Sounds good. I think that's the way we meant to implement it anyways.

**Comment by sbaechler** [comment]
Before we start implementing this we should first discuss how Thumbor should deal with high (or low) dpr images. @heynemann suggests that if a user requests a 300x300 image and the dpr is set to 2, then the response would be a 600x600 image. This would mean that internally Thumbor would use display independent pixels.
I think this makes sense and would simplify processing. Especially if later on the `Downlink` and `Save-Data` hints are active as well. A Downlink value of 0.5 should reset any high dpr value back to 1. This way, if I have set a crop rule and later on the dpr is changed, then the set crop values still apply because they are always relative to a dpr of 1.

**Comment by sbaechler** [comment]
I have started working on this issue: https://github.com/sbaechler/thumbor/tree/feature/hi-dpr
In fact, I had parts of it in a filter I'm working on. But it would be better if hi-dpr handling was done in Thumbor itself so it is consistent.

The capability is added as a filter which just sets a global dpr value. That value is 1 by default so it doesn't change current behavior.
The dpr value is stored in `context.request.dpr` as request parameter. If someone has a better idea then please tell me. It needs to be somewhere that is available during the full lifecycle of the request.

I added about 10 test cases, but this feature would need a lot more testing. I had to make some adjustments to the Transformer class.

I had to adjust the FilterTestCase base class as well so the filter are executed at the right time. There is still an issue with the test class because the filter has access to the Transformer class while it shouldn't have.

**Comment by heynemann** [comment]
Closing this as we are tracking this in #673 

If you have any further questions on this issue, please reopen it.

**Comment by Enalmada** [comment]
While trying to learn about client hints and responsive images I stumbled upon this: https://web.wurfl.io/#image-engine and just noting it here for an example of what thumbor would probably ultimately want to be capable of also.
