### ISSUE TITLE
URL Samples to work with

### ISSUE THREAD

**Issue by heynemann** [thumbor/thumbor#603]
Hey thumbor users,

I want to get a test suite for thumbor's URLs. I would like it to be as comprehensive as possible. It would be awesome if you guys could put URL formats here (unicode, encoded, unencoded, etc).

That way we can make sure thumbor works as expected for everyone.

/cc @masom @okor #602 #598 #601 #599 #593

**Comment by ekoka** [comment]
Hey @heynemann,
I'm not certain to understand what you need us to do, but I believe that URLs should be provided to `Crypto.generate()` as unicode objects like this:

```python
safe_url = crypto.generate(u'some/path/to/comme-ci-comme-çà.png')
 ```
It is my understanding that the sequence to encode an URL should generally go as follows:

Unicode object (if you start with one) -> UTF-8 encoding -> URL-encoding

Of the 3 strings, only the Unicode object will be natively identifiable by Python and will enforce some kind of check on characters upon inputs. The other two are seen as simple 8-bit strings (aka "normal" strings). They won't be recognized as being of a particular encoding and won't enforce any kind of check for the characters that are inserted. That is, you can do this `type(u'my_string') is unicode` whereas you can't `type('my_utf8_string') is utf8`. Also, if you have the string "\xC3\xA9" Python doesn't realize that you're intending to work in UTF-8 here. Only when you try the UTF-8 decoder that the validity of the string for that encoding will be tested:

```python
s = '\xC3\xA9'
to_unicode = s.decode('utf8')
```
For that reason, it seems to me that only an unicode object can guarantee that Thumbor receives what the user actually intended to provide.
 
Now, of the two 8-bit strings (utf8-encoded and url-encoded), only UTF-8 uses a set of codes to represent characters that is directly understood by Python i.e. `'\xC3\xA9'` is recognized directly as a sequence of two hex numbers within the string, whereas "%C3%A9" doesn't mean anything special. Because of this, Python sees `'\xc3\xa9'` as the equivalent of `'\xC3\xA9'`, whereas `'%C3%A9'` and `'%c3%a9'` are seen as completely different. Because of this I think that utf8 strings are safer to use for calculating hash based keys.

The problem though with asking users to provide their own 8-bit strings to generate those safe urls is that, as we've seen,  Python cannot distinguish between a latin1 string and an UTF-8 one. So the strings may come in all sorts of possible encodings. This is not desirable. Better ask them to provide Thumbor with strings in a format that Python understands universally, and that is unambiguous and predictable in its representation, regardless of the encoding they currently have set in their environment (latin1, utf-8, or other). Imo, Unicode is the obvious choice. So once you receive the Unicode object inside `Crypto.generate()`, then you encode in UTF-8 and use that 8-bit string as the basis for everything else.

Based on all that I think the format that would be desirable to work with at the API level is simply unicode:

```python
path = u"path/to/some/file/named/comme-ci-comme-çà.png"
crypto.generate(path)
# and from that point forward, hidden away from users
# 1- encode to utf-8: path = path.encode('utf8')
# 2- do everything that needs to get done
# 3- finally, before returning the string to the user, url-encode it: urllib.quote(path)

# and when receiving the url from Tornado
# 1- url-decode it first, which will give you back the original utf8 string, since that's the encoding it was created from
# 2- decrypt the key and compare to path/or encrypt the path and compare to key
# 3- do everything that needs to get done
```
