### ISSUE TITLE
How many http requests can thumbor handle at a time ?

### ISSUE THREAD

**Issue by vishaalgc** [thumbor/thumbor#630]
Im just testing thumbor past recent days, so i made this server in ubuntu and POST,DELETE,PUT etc works fine. I just wanted to know how much load at a time this thumbor server(running in oracle VM) can handle for a start so that i can integrate this in real time into other application

**Comment by masom** [comment]
It is highly dependent on the caching setup and the VM capacities ( ram, cpu, bus size ).

Thumbor is highly CPU bound when manipulating images.

popkey.co's cluster handled over 5 000 req/s with a polymorphic setup using AWS ELB, EC2 and Elasticache.

A typical setup would look like this:

- ELB load balancer
- EC2 instances ( c3.2xlarge )
- S3 as the image source, using the HTTP loader.
- Redis as the source storage
- Redis as the result storage

Redis is a great cache to use when clustering thumbor. By having results and source stored in separate redis servers you are able to horizontally scale up and down with the demand. The spin-up time of thumbor is dramatically reduced since each new instance has access to a warm cache and contribute to the cluster once a thumbnailing operation is complete.

**Comment by masom** [comment]
Thumbor itself will not be the bottleneck in the requests per second metric. That number will usually hover around ~15 req/sec when actively thumbnailing with no caches since the load is CPU-bound.

**Comment by vishaalgc** [comment]
I just tried to load a 33MB stored image file randomly using many http get requests and it froze my VM(thumbor server). i think its bound to happen. But didnt find any issue on loading a 4MB image. So i think this 15req/sec is perfect as you just said on an average. Say if i have to go with filesystem but not redis what requirements do you want me to start with and consider further ?

**Comment by masom** [comment]
If your thumbor installation will handle large images turning on the thread pool will greatly help preventing a single instance running out of CPU/RAM ( basically a DDOS ).

See https://github.com/thumbor/thumbor/blob/master/thumbor/config.py#L86

Set this to 2x the CPU and you should see a "better" behaviour from thumbor when large images / resources are being processed. You will have to figure out which value actually works best with your setup.

Using the filesystem to store results and sources will work although it will not let you take advantage of clustering technologies like HAProxy / http reverse proxy.
