### ISSUE TITLE
Improve HTTP Loader - Cache

### ISSUE THREAD

**Issue by qsomazzi** [thumbor/thumbor#646]
Hello,

I currently use thumbor in a project but, we have a caching issue with the HTTP loader.
What do you think about implementing a Cache validation system with the header {if-modified-since} in the loader ?

**Comment by masom** [comment]
@qsomazzi could you explain what problem you are facing?

Usually thumbor should not cache at the http loader but with result storage and storage classes that allow caching both the final result and the original file.

This is the current media loading flow: `loaders -> storages -> result_storages`

**Comment by qsomazzi** [comment]
Thanks @masom for your answer,

My user's work is to make an image, drop them a one place, and actualize it sometimes, keeping the same filename. 
So when I want to load their images and store the source image in storage the first time, everything works, but then, they change it. And this time the 'source' image is already in the storage, so we don't try to load it from the HTTP loader.

That's what I think the cache validation on the HTTP loader seems a great idea for me :)

**Comment by masom** [comment]
This specific use case will require some custom logic to accomplish this.

The loaders are completely stateless and are not being involved with the thumbor request cycle if the storage or result storage has a cache hit.

You would need to implement a storage and result_storage class that will validate the cache before returning the buffer.

Cache invalidation on the loaders is not feasible as thumbor will not call it if the storage or result storage returns a buffer.

**Comment by qsomazzi** [comment]
I've understand better where this should be done thanks to you, now I wonder if this could be done as a thumbor feature rather than a custom logic. I think i may not be facing this issue alone.
What do you think ?

**Comment by masom** [comment]
Usually the source of an image does not change. You could set your cache ( like redis or memcache ) to be something like 30 minutes instead of infinite and it would give you something very close to what you are looking for.

Validating the source image on every call to a storage will result in performance degradation for thumbor.

We currently try to encourage generic behaviour in the core with the ability for end-users to extend / improve with plugins / hook points. This reduces the size of the thumbor core allowing us to move faster.

https://github.com/thumbor-community has a few projects extending the thumbor core to support different use-case.
