### ISSUE TITLE
Image rotate with RESPECT_ORIENTATION

### ISSUE THREAD

**Issue by hhankj2u** [thumbor/thumbor#745]
### Thumbor request URL
http://192.168.1.200:8000/unsafe/test.jpg

### Expected behaviour
Image rotate and keep original width x height

### Actual behaviour
Image still rotate, but the height has been cropped ([Original file] (https://onedrive.live.com/redir?resid=2E9D88BDC88F65A7!180792&authkey=!ABaTTOyPw7w8ERA&v=3&ithint=photo%2cjpg))
![result](https://cloud.githubusercontent.com/assets/10140299/15821948/27dbd51e-2c1d-11e6-9012-4c1caa4a1268.png)

### Operating system
Centos 6.7
Thumbor v6.0.1 (22-Mar-2016)

### Your thumbor.conf
RESPECT_ORIENTATION = true

**Comment by Sparc145** [comment]
I believe I am experiencing the same issue with thumbor 6.0.1 and master as well.

The issue occurs when the image being passed to thumbor is saved in one orientation (ex landscape) with EXIF data to rotate the image to another orientation. This commonly occurs with the stock android camera app, so it's a fairly common situation. I've only noticed this on TIFF format JPEG but that may be from my limited sample set.

I have attached another example of this issue. This is saved in landscape, and should be rotated to position 6 via EXIF data so that the vent is at the bottom of the photo.
![20160601_174939](https://cloud.githubusercontent.com/assets/15718425/15878239/3f873544-2cce-11e6-8522-9dc98350e108.jpg)

**Comment by guilhermef** [comment]
I'll take a look at this on the weekend.
Can you pinpoint the issue in the code ?

**Comment by Sparc145** [comment]
Thanks for looking into this. I unfortunately have not been able to pinpoint the issue in code, but I am thinking it is related to the pillow engine.

**Comment by guilhermef** [comment]
It was a bug, https://github.com/thumbor/thumbor/commit/b160a9b65a026f069ed0ebe22fc5cf7fc89d01ad should fix this.
Sorry.

**Comment by Sparc145** [comment]
I confirmed the fix works on several images we previously saw with this issue. Thanks for the quick fix!
