### ISSUE TITLE
Flush result storage cache (api or http delete method)

### ISSUE THREAD

**Issue by rogeriollacerda** [thumbor/thumbor#766]
Hi, I'm using 20 thumbor dockers on the same machine. My result storage is a local directory. Cold I flush the cache of an specific image by http request? If not, how can I solve something like that?

Tks

**Comment by guilhermef** [comment]
Your storage is probably mounted on these docker instances,
It would be better to have another application dealing with the cache flush.

**Comment by luisdavim** [comment]
I would welcome an invalidation API.

**Comment by rogeriollacerda** [comment]
For while, I'm using a little Go app running in Thumbor servers that I can flush using curl + image URL.

**Comment by MattBlissett** [comment]
This isn't HTTP, but if anyone else needs a quick fix to delete cache files from the filesystem, I have a script here:

https://gist.github.com/MattBlissett/2350ba272d908d0da6c3cff3a51367f2

**Comment by heynemann** [comment]
Sorry guys, we have an invalidation API at globo.com. Why don't we have it at thumbor? Because there's no sane way for an invalidation API that would work with all storages, loaders, etc. How to invalidate all the images that thumbor has generated from a previous image? Invalidating is VERY dependent on how you store your images.
At globo.com we store all the variants of an image in a folder with the original image name. That way, when invalidating, we delete this folder and purge all cache.

I don't think this is an attribution of thumbor.

If you have any further questions on this issue, please reopen it.

**Comment by jimas14** [comment]
@heynemann Reviving this old thread because my implementation is running into issues with invalidation. Could you please elaborate on:
>At globo.com we store all the variants of an image in a folder with the original image name. That way, when invalidating, we delete this folder and purge all cache.
We use S3 for result storage and store objects with the full resize path including the hash. The suffix of the path is the original name I want to be able to purge by, which is nearly impossible in S3 without listing all of the objects. If we could somehow store the path with the _prefix_ being the original name that would solve all our issues. This seems similar to the solution you describe but I can't find anything in Thumbor configs that allows you to specify the result storage path, let alone for S3 result storage.

If you could please offer some guidance I would greatly appreciate it 🙏
