### ISSUE TITLE
How AUTO_WEBP works?

### ISSUE THREAD

**Issue by fmunteanu** [thumbor/thumbor#867]
I'm running Thumbor 6.2.1 with Nginx and Supervisord in a CentOS7 64 bits environment.
I'm trying to understand how AUTO_WEBP setting works. From the documentation:
> This option indicates whether thumbor should send WebP images automatically if the request comes with an "Accept" header that specifies that the browser supports "image/webp".

The issue I have is the wrong image content type and lenght. If AUTO_WEBP is enabled and the request meets the documented conditions, I should see a significant content length reduction. Basically, if I save the image or verify its content length with curl, it should be a lot smaller. Also, the content type should show as "image/webp". Unfortunately, it is not.

While looking at Nginx logs, I see the $http_accept contains "image/webp":
> [23/Feb/2017:15:37:41 +0000] "GET /4vsKo4fsQDMqYzslODQEDNmnYB4=/cdn.com/images/test.jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.54 Safari/537.36" text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8

CURL for /4vsKo4fsQDMqYzslODQEDNmnYB4=/cdn.com/images/test.jpg, I get 180KB instead of 74KB. The content type should show as "image/webp":

```
HTTP/1.1 200 OK
Cache-Control: max-age=2592000,public
Content-Length: 180965
Content-Type: image/jpeg
Date: Thu, 23 Feb 2017 15:59:47 GMT
Etag: "52233cac8daa1fd92feb5250b5a2d25bea1f9e22"
Expires: Sat, 25 Mar 2017 15:59:47 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000
Vary: Accept
Connection: keep-alive
```

CURL for /y9X8r_RITBm_bxTSF9x1Muz72UM=/filters:format(webp)/cdn.com/images/test.jpg, I get 74KB and proper content type:

```
HTTP/1.1 200 OK
Cache-Control: max-age=2592000,public
Content-Length: 78948
Content-Type: image/webp
Date: Thu, 23 Feb 2017 16:03:50 GMT
Etag: "fcd3f3587f59bf9ac78b505e1f1bad6cbcd2bc26"
Expires: Sat, 25 Mar 2017 16:03:50 GMT
Server: nginx
Strict-Transport-Security: max-age=31536000
Connection: keep-alive
```

Current Thumbor configuration:

```
ALLOW_OLD_URLS = False
ALLOW_UNSAFE_URL = False
AUTO_WEBP = True
DETECTORS = [
	'thumbor.detectors.face_detector',
	'thumbor.detectors.feature_detector',
	'thumbor.detectors.glasses_detector',
	'thumbor.detectors.profile_detector'
]
OPTIMIZERS = [
	'thumbor.optimizers.jpegtran'
]
JPEGTRAN_PATH = '/usr/bin/jpegtran'
HTTP_LOADER_MAX_CLIENTS = 1024
MAX_AGE = 2592000
MAX_AGE_TEMP_IMAGE = 60
STORAGE = 'thumbor.storages.file_storage'
STORAGE_EXPIRATION_SECONDS = 300
RESULT_STORAGE = 'thumbor.result_storages.file_storage'
RESULT_STORAGE_EXPIRATION_SECONDS = 1800
```

**Comment by okor** [comment]
@fmunteanu Hi there : )

As you quoted from the documentation, auto webp works via the accepts header. So if you want to test Thumbor the curl command would be something like: `curl --header "accept: image/webp,image/*,*/*;q=0.8" -I "<yourhost>/4vsKo4fsQDMqYzslODQEDNmnYB4=/cdn.com/images/test.jpg"`

Without the header for webp, the url above will return whatever format the source image is in. In this case, jpeg. Chrome and Opera adds those accept headers to image requests, so you can also try viewing the response content type in Chrome vs Firefox.

And when you explicitly state the format, like `format(webp)` it will always return webp. 

Does that clear things up?

**Comment by fmunteanu** [comment]
@okor Hi Jason,

When I opened the image into browser, it clearly shows as "image/webp" into Nginx logs:
> [23/Feb/2017:15:37:41 +0000] "GET /4vsKo4fsQDMqYzslODQEDNmnYB4=/cdn.com/images/test.jpg HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.54 Safari/537.36" text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,/;q=0.8

But when I saved the image to disk, it had the regular JPEG size/format, instead of WEBP one. To my understanding, it should automatically push the proper WebP format when AUTO_WEBP is enabled?

**Comment by okor** [comment]
Ok, so, if you are trying to verify that a webp image is being served to your browser the best and easiest way is to use Chrome's built in developer tools, look at the Network tab. Make sure the "type" option is enabled.

![screen shot 2017-02-23 at 4 16 17 pm](https://cloud.githubusercontent.com/assets/142910/23279497/846ed4ea-f9e3-11e6-8765-848ce8d097e0.jpg)

You can also verify the size of the image file, which will often be smaller than it's non-webp counterpart. Compare the same page to Firefox, it will be different format/filesize.

But here's the thing (buckle up), depending on the browser (and maybe OS) different things can happen when you try to save an image to disk. Like, Chrome for a long time would convert any webp image you tried to download to a png. I'm sure they were just trying to make it easier for "normal" users to use image files they ... acquired from sites. Currently, in Chrome on OSx, if I try to drag a webp image to my desktop it will not save. I have to right click, save as ... then in the save dialog you are presented with two options ... save as JPEG or "all files". Both of those options ... regardless of what options I select or how I name the file `saves the image in webp format`. However ... gawd ... OSx will tell you this file is a JPEG is you open the info panel. That is not correct, it's webp, they are just guessing by looking at the file extension which could be ... PDF or exe. This is the "wrong way" to identify the format of a binary file. Instead, they should probably be looking at "magic bytes" if they want to be accurate. If you are using Windows I have no idea what they do but I'd hazard to guess they do the same thing.

Now. Keep in mind your source image has the extension of "jpg", "jpeg" or "png" (right?) so if you save the file to your disk OSx assumes that format. You might notice that it fails to generate an image thumbnail ... that's because OSx doesn't have built in support for webp so it can't generate a thumbnail for the image (another round about way of verifying it's webp). Chrome gives webp viewing to you but the os doesn't understand the format really.

If you drag that saved file back into a Chrome tab you should see an image. Do the same thing on Firefox and it will just redownload that sucker because ... it doesn't understand webp.

So, downloading images from the browser in an attempt to verify they are webp may not be the best method ... at least not the easiest method of verifying the format.

Also, if you have ImageMagick installed it will give you a command called `identify`. You can just run `identify probablywebp.jpg` and it will very helpfully tell you the image format is PAM. Which .. is wrong. It's actually webp. Even if you have webp support or convert an image with imagemagick directly it will tell you the output is PAM.

Probably the most full proof way to verify an image is actually webp (other than the easy way, Chrome) is to view the file in a hex editor - like the free "Hex Fiend". Open the webp blob and in the right hand side you will see some gibberish like `RIFFÑaWEBPVP8X` ... which means you have in your possession a webp image. If it says something like `JFIF`, then that is a jpeg. If you see PNG ... it's a png.

If you are worried about the browser converting the image somehow while saving, you can use curl.  `curl --header "accept: image/webp,image/*,*/*;q=0.8" "<yourhost>/4vsKo4fsQDMqYzslODQEDNmnYB4=/cdn.com/images/test.jpg" > test.webp` That's going to be webp right there.

Does that help?

**Comment by fmunteanu** [comment]
@okor Hi Jason,

Thanks for the guidelines. For sanity reasons, I will disable the AUTO_WEBP option and have it served explicitly with filters:format(webp). I believe AUTO_WEBP option might also impact overall performance. Please let me know your thoughts on that.

**Comment by okor** [comment]
@fmunteanu AUTO_WEBP can in fact be a confusing option if you don't understand everything that happening, for sure. And there are also some nuances on caching where you will need to make sure your CDN and/or caching layer will vary on the accepts header.

If you are creating `srcset`s *without* AUTO_WEBP you create roughly double the markup in your DOM which can get pretty non-trivial in size if you are using for instance the picture element to do art direction + responsive + dpi (exactly what I do for Vox Media sites) then the size can add up. GZIP should help quite a bit for over the wire document size ... but it's something to consider. It might affect decode/parse times.

Also, if you are not using `srcset` then you are probably writing urls with javascript, doing some kind of webp client support check to decide what format you should give to the user. That means you have to either allow `unsafe` mode on Thumbor (exposes you to abuse/attack) or you have to create some sort of server side api to help generate crypto hashed thumbor urls and return urls in JSON ... then render them, etc.

My personal opinion is that explicit web is easier to work with, just make sure to use srcsets so the browser can handle format support/selection.

**Comment by fmunteanu** [comment]
@okor Hi Jason,

I will run tests on a test environment with AUTO_WEBP=True and see what is the performance impact. I certainly like the idea of saving a lot of bandwidth and serve pages much faster to users, just Chrome has a 52% global market. Not to mention the Android mobile world.

**Comment by okor** [comment]
@fmunteanu Yes, since Chrome usage is so high (like 70% for Vox Media, 50% global http://gs.statcounter.com/) it makes sense. The front end performance difference is normally quite large. But image compression is incredibly complex and it's difficult to say that one thing will work better or worse ... you generally need to know what's going in to even make a recommendation. 

If you have an editorial team that uploads a bunch of PNGs, those can be converted to webp naively and will result in much smaller files. With JPEG it depends a lot on whether the JPEG was optimized first or not. 

But as a practical and simple answer, I think that using some variant of webp will result in significantly smaller and faster images for most people. And that's the point, faster web pages. I've been using webp at Vox Media sites for quite a while and I'm largely happy with it.

**Comment by vinhlh** [comment]
@okor how about the WebP quality factor did you use?
I've tried with quality 90, doesn't have a noticeable change.

On local, I tried with `-lossless`, but the size of images even increase.

**Comment by vinhlh** [comment]
And one thing about saving WebP, currently, this is my setting, If `Accept` header `begins` with `image/webp`, serves WebP images; instead, serves JPEG images.
So if you click `Save As`, it will seems JPEG images to local computer (I guess the request to save the image don't have `image/webp*` header, could be `text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8`
(tested on Chrome/ MacOS).

https://medium.com/@vinhlh/how-i-apply-webp-for-optimizing-images-(9b11068db349#.v8qgftram)

**Comment by okor** [comment]
@vinhlh I happen to use the webp quality setting of `80` but I should stress that the quality level is just a best guess that you are making. The quality setting doesn't mean "80% smaller than original", it means something more like "using this encoders algorithms, with 20% aggression". The math behind the scenes is quite complex, different for each image format and I don't understand it all. But I think that's an important note to make. It's a best guess. So try a setting and see if you get results that you like.

The `lossless` option as the name implies tries to convert the image without any compression at all so in some cases it may be larger than the original. I did some tests a while back on a large set of images (tens of thousands) and webp resulted in smaller images the majority of the time. I've found that "complex vector like" and "8 bit style" images are occasionally messed up by webp with default settings. Thumbor doesn't have a setting for this yet but I've found that the `deblocking` encoder setting can be tweaked to fix this.

As far as your settings and the image you are downloading, I'm not sure I understand. Are you asking a question? If you are trying to verify that the image is webp the easiest way is to look in the network tab under the content "type" data. If you have a website running with thumbor or some sample urls that should be webp I can quickly verify if it's working or not.

You're medium post link is 404'ing for me.

**Comment by vinhlh** [comment]
Yep, I see, I also just measured by eyes If the quality is similar 💃 
I also tried SSIM, my WebP images with quality factor = 90% has around 98.5% SSIM, compared to the original images.

About downloading WebP images, it's just a trick I am using for: users are able to download and view the image.
I also updated the link

**Comment by okor** [comment]
@vinhlh Oh, excellent. And nice blog post. I never know how much people know about things like webp/ssim/compression/etc so I try not to assume anything. You're clearly up to speed.

And wrapping image elements in a link to their JPEG or PNG counterparts will probably make them easier to share, for sure.

Glad to hear you'd had success with webp and thumbor : )
