### ISSUE TITLE
Multi tenant support

### ISSUE THREAD

**Issue by onefriendaday** [thumbor/thumbor#868]
I would like to share the idea of having multi tenant support for thumbor. So you can have multiple secure tokens for your clients and revoke access individually.
I prepended tenant_id to the url and query the token in DynamoDB.
/TENANT_ID/secure_token/image_path

Here are the required changes:
https://github.com/storyblok/thumbor/commit/61d02214bb174f0d2a24b10913070cdfe9a4f761

I was wondering if you would realize that differently?

**Comment by mpilar** [comment]
My observations:
For me this seems like a somewhat naive solution. What if different tenants have different AWS accounts? Different S3 buckets? 

Hardcoding the DynamoDB configuration and access without abstraction is also very brittle, there's also no caching of the data, If one of your tenants gets most of the traffic vs others this can be fairly bad for DynamoDB performance [see here](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/GuidelinesForTables.html?shortFooter=true). There's no encryption of the data in DynamoDB and also does not seem to support (at a glance) key rotations.

If you're just concerned about signature tenancy, I think this would be better off being a patch to [libthumbor's url_signers module](https://github.com/thumbor/libthumbor/tree/master/libthumbor/url_signers). Or even a signer in [tc_aws](https://github.com/thumbor-community/aws). 

There is nothing that says that the tenant cannot be part of the signature (a la /etc/shadow) with a separator so something like: `$<signature version>$<Tenant id>$<key id>$<signature>`

This provides:

- Versioning of the signature (so that different algorithms/tenant signature providers) can be implemented.
- Tenant ID for lookup
- Different versions of the key_id for legacy URLs
- the actual signature

I think this would provide a robust solution.

**Comment by masom** [comment]
Signers are actually pluggable, it is possible to use a different url signing strategy that includes a tenant id, etc.

**Comment by miracle2k** [comment]
@masom Any pointer has to how to do this? Allow multiple signing keys?

**Comment by masom** [comment]
@miracle2k 
A way to achieve this with minimal modifications to thumbor would be to write a new signer that generates a hash with both the tenant id and the signature.

```

```

**Comment by miracle2k** [comment]
@masom Thanks that is helpful.

**Comment by gingerlime** [comment]
I know it's an old thread, but I hope someone can help.

What if you want to keep the thumbor client as-is (i.e. not having to modify the signing on the client library, e.g. [libthumbor](https://github.com/thumbor/libthumbor)), and use the domain portion as a tenant-identifier. e.g. `https://tenant1.example.com/{signature1}/...`, `https://tenant2.example.com/{signature2}/...`?

The current signer seems to take only the path portion of the url, after removing the signature, so plugging a different signer won't be sufficient.

Any suggestions on how to achieve a multi-tenant setup that clients can continue to use the same client libraries, and detect the tenant from the domain portion of the URL?

I guess the server can cycle through all possible tenant keys until there's a match, but this probably won't be very efficient... (I can try to benchmark it though, so maybe it's not *that* slow in the grand scheme of things)

**Comment by heynemann** [comment]
Without thinking too much about it, it seems to me a problem better solved by a proxy that identifies who the user is by the tenant and passes the user's token (or whatever you use as a key) as header for thumbor when creating new images. That way you can verify if the request contains the auth header and find what the security key for that user is, then use it.

Since it's an advanced case of using thumbor (hosted thumbor, I believe), it's hard to help without further detail (and time invested).

Hope it helps.

**Comment by gingerlime** [comment]
Thanks @heynemann.

Yes, I'm toying with the idea of a hosted thumbor setup for multi-tenants. I actually thought about a simple proxy layer, but as @mpilar aptly noted, this isn't the only barrier, because you also need to account for different backend stores (AWS accounts, S3 buckets etc)... not sure if it's easily solvable with the way thumbor works.

Of course, you can have a separate VPS or instance for each tenant, but even with docker, there's quite a considerable overhead involved, so scaling can become tricky.

I'm just exploring this direction at the moment, so I thought I would ask. Any pointers or thoughts would be appreciated. I think there's a market/potential for people to use thumbor who don't want to handle the hosting aspects of it.

**Comment by heynemann** [comment]
Btw, if you decide to implement your own app, you can pass it to `thumbor-cli` with `-a full.path.to.app`.

**Comment by gingerlime** [comment]
Thanks a lot @heynemann. I really appreciate it. That's very helpful.

So it seems that implementing an app means taking care of all request handling, but still using the core thumbor methods to do the actual image processing etc, right? This seems like a reasonable approach. Of course, it might make it harder to keep up with any API changes etc and make sure things are all working, but I imagine the core API doesn't change that frequently, right? 

I'll take a look at the refactor branch as well. I'm still not very familiar with the thumbor internals to be honest, but I hope I can figure things out and contribute more to the project over time.
