### ISSUE TITLE
POST an image and get the transformed image back

### ISSUE THREAD

**Issue by mpdude** [thumbor/thumbor#880]
Is it possible to provide an image in a POST request, have that image processed and returned?

I don't need the `/image` endpoint for persistent image storage, and it would be great if I don't have to make several HTTP requests for the upload, transformation and image removal.

**Comment by heynemann** [comment]
No, this is not something thumbor supports and I think it's a little outside our scope. If you need ephemeral storage, there are a lot of people using redis for this, since you can define how large you want storage to be (the amount of memory that redis supports).

If you have any further questions on this issue, please reopen it.
