### ISSUE TITLE
Remove background colors?

### ISSUE THREAD

**Issue by mackelito** [thumbor/thumbor#992]
I have been searching issues and googling but cant really figure out if this is even possible..

Let´s take this image as example
![08](https://user-images.githubusercontent.com/598463/31268709-da8448b0-aa7d-11e7-9ca9-5f10f1697be1.png)

So the question is... Can I remove the white background + shadow and have it transparent instead?

**Comment by mackelito** [comment]
Not much activity here :(
I was kind of hoping that we could develop a plugin or so to achieve this..

**Comment by Savar** [comment]
Not sure if this is valuable because it would always be a guessing. But for this you might want to check stuff like http://blog.sodhanalibrary.com/2015/05/detect-background-color-of-image-using.html?m=1 if you plan to develop something.

Am 6. November 2017 08:44:10 MEZ schrieb Markus Thiel <notifications@github.com>:
>Not much activity here :(
>I was kind of hoping that we could develop a plugin or so to achieve
>this.. 
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/thumbor/thumbor/issues/992#issuecomment-342069565

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by mackelito** [comment]
thx for the link but our need are more sophisticated than just a color :)
We have it working in a Java based platform but we need more features :)

**Comment by heynemann** [comment]
I don't think this is a filter that belongs in thumbor's codebase. I would love to see it implemented, but as a community project in https://github.com/thumbor-community.

Please reopen this issue if you have any other questions on this subject.
